/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import Dao.QLThuVienDao;
import Dao.SachDao;
import Entity.Sach;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author duyvo
 */
public class QLSach extends javax.swing.JPanel {
   List<Sach> list = new ArrayList<>();
    SachDao sdao = new SachDao();
    int row = 0;
     String connectionUrl = "jdbc:sqlserver://localhost:1433;"
            + "databaseName=QUANLYTHUVIEN1;"
            + "user=sa;password=123;"
            + "encrypt=true;"
            + "trustServerCertificate=true;";
    /**
     * Creates new form QLSach
     */
    public QLSach() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        myButton1 = new button.MyButton();
        myButton3 = new button.MyButton();
        myButton6 = new button.MyButton();
        myButton5 = new button.MyButton();
        myButton8 = new button.MyButton();
        myButton2 = new button.MyButton();
        myButton4 = new button.MyButton();
        myButton7 = new button.MyButton();
        txtMaSach = new button.textfield.TextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();
        txtTacGia = new button.textfield.TextField();
        jLabel8 = new javax.swing.JLabel();
        chkVH = new javax.swing.JCheckBox();
        chkDL = new javax.swing.JCheckBox();
        chkSHelp = new javax.swing.JCheckBox();
        chkLS = new javax.swing.JCheckBox();
        chkKD = new javax.swing.JCheckBox();
        chkTA = new javax.swing.JCheckBox();
        chkGT = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        chkTrHoc = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        txtTenSach = new button.textfield.TextField();
        jLabel11 = new javax.swing.JLabel();
        txtNXB = new button.textfield.TextField();
        jLabel12 = new javax.swing.JLabel();
        txtGhiChu = new button.textfield.TextField();
        header = new component.menu_1();
        QLNhanVIen = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        txtTimKiem = new button.textfield.TextField();
        jLabel13 = new javax.swing.JLabel();

        main.setBackground(new java.awt.Color(255, 204, 204));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bx-plus.png"))); // NOI18N
        myButton1.setColorClick(new java.awt.Color(255, 204, 153));
        myButton1.setRadius(10);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        main.add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 560, 50, 45));

        myButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bx-pencil.png"))); // NOI18N
        myButton3.setRadius(10);
        myButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton3ActionPerformed(evt);
            }
        });
        main.add(myButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 560, 50, 45));

        myButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bx-last-page.png"))); // NOI18N
        myButton6.setRadius(10);
        myButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton6ActionPerformed(evt);
            }
        });
        main.add(myButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(996, 560, 50, 45));

        myButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bx-chevron-right.png"))); // NOI18N
        myButton5.setRadius(10);
        myButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton5ActionPerformed(evt);
            }
        });
        main.add(myButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(934, 560, 50, 45));

        myButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bx-chevron-left.png"))); // NOI18N
        myButton8.setRadius(10);
        myButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton8ActionPerformed(evt);
            }
        });
        main.add(myButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(872, 560, 50, 45));

        myButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bx-x.png"))); // NOI18N
        myButton2.setRadius(10);
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });
        main.add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 560, 50, 45));

        myButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bxs-news.png"))); // NOI18N
        myButton4.setRadius(10);
        myButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton4ActionPerformed(evt);
            }
        });
        main.add(myButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, 50, 45));

        myButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/first-page-regular-24.png"))); // NOI18N
        myButton7.setRadius(10);
        myButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton7ActionPerformed(evt);
            }
        });
        main.add(myButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 560, 50, 45));

        txtMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSachActionPerformed(evt);
            }
        });
        main.add(txtMaSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 267, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        jLabel7.setText("Mã sách:");
        main.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        tblSach.setBackground(new java.awt.Color(204, 204, 204));
        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Tác Giả", "Nhà xuất bản", "Thể loại", "Ghi chú"
            }
        ));
        tblSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblSachMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblSach);

        main.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 570, 401));

        txtTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTacGiaActionPerformed(evt);
            }
        });
        main.add(txtTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 267, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        jLabel8.setText("Tác giả:");
        main.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        chkVH.setText("Văn học");
        main.add(chkVH, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 80, 30));

        chkDL.setText("Địa lí");
        main.add(chkDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 80, 30));

        chkSHelp.setText("Self help");
        chkSHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSHelpActionPerformed(evt);
            }
        });
        main.add(chkSHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 80, 30));

        chkLS.setText("Lịch sử");
        main.add(chkLS, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 80, 30));

        chkKD.setText("Kinh dị");
        main.add(chkKD, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 80, 30));

        chkTA.setText("Tiếng Anh");
        main.add(chkTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 102, 30));

        chkGT.setText("Giả tưởng");
        main.add(chkGT, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 110, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        jLabel10.setText("Thể loại:");
        main.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        chkTrHoc.setText("Triết học");
        main.add(chkTrHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 80, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        jLabel9.setText("Tên sách:");
        main.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        txtTenSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSachActionPerformed(evt);
            }
        });
        main.add(txtTenSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 270, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        jLabel11.setText("NXB:");
        main.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        txtNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNXBActionPerformed(evt);
            }
        });
        main.add(txtNXB, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 267, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        jLabel12.setText("Ghi chú:");
        main.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, -1, -1));

        txtGhiChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGhiChuActionPerformed(evt);
            }
        });
        main.add(txtGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 529, 270, 100));

        QLNhanVIen.setBackground(new java.awt.Color(102, 102, 102));
        QLNhanVIen.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        QLNhanVIen.setForeground(new java.awt.Color(255, 255, 255));
        QLNhanVIen.setText("Quản lí sách");
        QLNhanVIen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QLNhanVIenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QLNhanVIenMouseExited(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(401, 401, 401)
                .addComponent(QLNhanVIen)
                .addContainerGap(404, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QLNhanVIen)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        main.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));
        main.add(lblDongHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1035, 623, 70, -1));

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });
        main.add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 153, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        jLabel13.setText("Tìm kiếm:");
        main.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
     insert();
    }//GEN-LAST:event_myButton1ActionPerformed

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
     update();
    }//GEN-LAST:event_myButton3ActionPerformed

    private void myButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton6ActionPerformed
     next();
    }//GEN-LAST:event_myButton6ActionPerformed

    private void myButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton5ActionPerformed
       last();
    }//GEN-LAST:event_myButton5ActionPerformed

    private void myButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton8ActionPerformed
     prev();
    }//GEN-LAST:event_myButton8ActionPerformed

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        delete();
    }//GEN-LAST:event_myButton2ActionPerformed

    private void myButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton4ActionPerformed
   clearForm();
    }//GEN-LAST:event_myButton4ActionPerformed

    private void myButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton7ActionPerformed
       first();
    }//GEN-LAST:event_myButton7ActionPerformed

    private void txtMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSachActionPerformed

    private void tblSachMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSachMousePressed
        if (evt.getClickCount() == 2) {
            row = tblSach.getSelectedRow();
         //   tab.setSelectedIndex(0);
            this.edit();
        }
    }//GEN-LAST:event_tblSachMousePressed

    private void txtTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTacGiaActionPerformed

    private void chkSHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSHelpActionPerformed

    private void txtTenSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSachActionPerformed

    private void txtNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNXBActionPerformed

    private void txtGhiChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGhiChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGhiChuActionPerformed

    private void QLNhanVIenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QLNhanVIenMouseEntered
        // TODO add your handling code here:
        QLNhanVIen.setForeground(new Color(255, 255, 0));
    }//GEN-LAST:event_QLNhanVIenMouseEntered

    private void QLNhanVIenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QLNhanVIenMouseExited
        // TODO add your handling code here:
        QLNhanVIen.setForeground(new Color(242, 242, 242));
    }//GEN-LAST:event_QLNhanVIenMouseExited

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        fillTable();
    }//GEN-LAST:event_txtTimKiemKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel QLNhanVIen;
    private javax.swing.JCheckBox chkDL;
    private javax.swing.JCheckBox chkGT;
    private javax.swing.JCheckBox chkKD;
    private javax.swing.JCheckBox chkLS;
    private javax.swing.JCheckBox chkSHelp;
    private javax.swing.JCheckBox chkTA;
    private javax.swing.JCheckBox chkTrHoc;
    private javax.swing.JCheckBox chkVH;
    private component.menu_1 header;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JPanel main;
    private button.MyButton myButton1;
    private button.MyButton myButton2;
    private button.MyButton myButton3;
    private button.MyButton myButton4;
    private button.MyButton myButton5;
    private button.MyButton myButton6;
    private button.MyButton myButton7;
    private button.MyButton myButton8;
    private javax.swing.JTable tblSach;
    private button.textfield.TextField txtGhiChu;
    private button.textfield.TextField txtMaSach;
    private button.textfield.TextField txtNXB;
    private button.textfield.TextField txtTacGia;
    private button.textfield.TextField txtTenSach;
    private button.textfield.TextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
 public void timkiem() {
        try {
            Connection con = DriverManager.getConnection(connectionUrl);
            PreparedStatement st = con.prepareStatement("select TenSACH,MaTG,MaNXB,MaTL,MOTA from Sach where TenSACH =?");
            st.setString(1, txtTimKiem.getText());
            ResultSet rs = st.executeQuery();
            list.clear();
            while (rs.next()) {
                //tạo 1 đối tượng Grade
                Sach sach = new Sach();
                sach.setMaSACH(rs.getString("MaSACH"));
                sach.setTenSACH(rs.getString("TenSach"));
                sach.setTacGIA(rs.getString("TacGia"));
                sach.setNXB(rs.getString("NXB"));
              //  sach.setTheLoai(rs.);       
                sach.setMOTA(rs.getString("GhiChu"));             
                //thêm điểm vào dsdiem
                list.add(sach);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
     private void fillTable() {
    DefaultTableModel model = (DefaultTableModel) tblSach.getModel();
    model.setRowCount(0);
    try {
         String keyword = txtTimKiem.getText();
         
            List<Sach> list = sdao.selectByKeyword(keyword);
     //   List<Sach> list = sdao.selectAll();
    for (Sach s : list) {
            Object[] row = {
                s.getMaSACH(),
                s.getTenSACH(),
                s.getTacGIA(),
                s.getNXB(),
                String.join(",", s.getTheLoai()),  // Join list of genres into a comma-separated string
                s.getMOTA()
            };
            model.addRow(row);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi truy vấn dữ liệu !");
        e.printStackTrace();
    }
}
     
     
     private void clearForm() {
        txtMaSach.setText(null);
        txtTenSach.setText(null);
        txtNXB.setText(null);
        txtTacGia.setText(null);
        txtGhiChu.setText(null);
        chkGT.setSelected(false);        
        chkTA.setSelected(false);
        chkVH.setSelected(false);
        chkTrHoc.setSelected(false);
        chkLS.setSelected(false);
        chkDL.setSelected(false);
        chkKD.setSelected(false);
        chkSHelp.setSelected(false);
    }
    
    private void edit() {
        try {
            String manv = (String) tblSach.getValueAt(this.row, 0);
            Sach nv = sdao.selectById(manv);
            if (nv != null) {
                this.setForm(nv);
                System.out.println("e:" +nv);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    
    
    private void setForm(Sach nv) {    
        txtMaSach.setText(nv.getMaSACH());
        txtTenSach.setText(nv.getTenSACH());
        txtTacGia.setText(nv.getTacGIA());
        txtNXB.setText(nv.getNXB());
        txtGhiChu.setText(nv.getMOTA());
        chkKD.setSelected(false);
        chkGT.setSelected(false);
        chkTA.setSelected(false);
        chkSHelp.setSelected(false);
        chkLS.setSelected(false);
        chkVH.setSelected(false);
        chkTrHoc.setSelected(false);
        chkDL.setSelected(false);
//        if (nv.getTheLoai().equals("KD01")) {
//            chkKinhDi.setSelected(true);
//        }
//        if (nv.getTheLoai().equals("SH01")) {
//            chkSelfhelp.setSelected(true);
//        }
        for (String theLoai : nv.getTheLoai()) {
            if(!theLoai.contains(",")){
                theLoai+=",";
            }
            for (String tl : theLoai.split(",")) {
                
                if (tl.equalsIgnoreCase("KD01")) {
                    chkKD.setSelected(true);
                    System.out.println("1: "+theLoai);
                }
                if (tl.equalsIgnoreCase("TrH01")) {
                    chkTrHoc.setSelected(true);
                    System.out.println("1: "+theLoai);
                }
                if (tl.equalsIgnoreCase("TA01")) {
                    chkTA.setSelected(true);
                    System.out.println("1: "+theLoai);
                }
                if (tl.equalsIgnoreCase("SH01")) {
                    chkSHelp.setSelected(true); 
                    System.out.println("1: "+theLoai);
                }
                if (tl.equalsIgnoreCase("LS01")) {
                    chkLS.setSelected(true);
                    System.out.println("1: "+theLoai);
                }
                if (tl.equalsIgnoreCase("GT01")) {
                    chkGT.setSelected(true);
                    System.out.println("1: "+theLoai);
                }
                if (tl.equalsIgnoreCase("DL01")) {
                    chkDL.setSelected(true);
                    System.out.println("1: "+theLoai);
                }
                if (tl.equalsIgnoreCase("VH01")) {
                    chkVH.setSelected(true);
                    System.out.println("1: "+theLoai);
                }
    //            System.out.println("a: "+theLoai);
            }
        } 
    }
    
    private Sach getForm() {
    Sach nv = new Sach();
    nv.setMaSACH(txtMaSach.getText());
    nv.setTenSACH(txtTenSach.getText());
    nv.setTacGIA(txtTacGia.getText());
    nv.setNXB(txtNXB.getText());

    // Khởi tạo danh sách thể loại
    ArrayList<String> theLoaiList = new ArrayList<>();

    // Kiểm tra từng checkbox và thêm thể loại tương ứng
    if (chkKD.isSelected()) {
        theLoaiList.add("KD01");
    }
    if (chkSHelp.isSelected()) {
        theLoaiList.add("SH01");
    }
    if (chkTA.isSelected()) {
        theLoaiList.add("TA01");
    }
    if (chkTrHoc.isSelected()) {
        theLoaiList.add("TrH01");
    }
    if (chkLS.isSelected()) {
        theLoaiList.add("LS01");
    }
    if (chkGT.isSelected()) {
        theLoaiList.add("GT01");
    }
    if (chkVH.isSelected()) {
        theLoaiList.add("VH01");
    }if (chkDL.isSelected()) {
        theLoaiList.add("DL01");
    }
    

    // Gán danh sách thể loại cho đối tượng Sach
    nv.setTheLoai(theLoaiList);

    // Gán mô tả
    nv.setMOTA(txtGhiChu.getText());

    return nv;
}
    
    
    private void insert() {
        Sach s = this.getForm();
    try {
        sdao.insert(s); // thêm mới
        this.fillTable(); // đổ lại bảng
        this.clearForm(); // xóa trắng form
        JOptionPane.showMessageDialog(this, "Thêm thành công!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Thêm thất bại!");
        e.printStackTrace();
    }
    }
     
      void update() {
        Sach s = getForm();
        try {
            sdao.update(s);
            this.fillTable();
            System.out.println(":");
            clearForm();
            JOptionPane.showMessageDialog(this, "Sửa thành công");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
    }
      
      private void delete() {

        String masach = txtMaSach.getText();
        
            try {
                sdao.delete(masach);
                this.fillTable();
                this.clearForm();
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
                e.printStackTrace();
            }
        

    }
         private void first() {
        this.row = 0;
        this.edit();
             showsgreenline(row);
    }

    private void prev() {
        if (this.row > 0) {
            this.row--;
            showsgreenline(row);
            this.edit();
        }
    }

    private void next() {
        if (this.row < tblSach.getRowCount() - 1) {
            this.row++;
            showsgreenline(row);
            this.edit();
        }
    }

    private void last() {
        this.row = tblSach.getRowCount() - 1;
        showsgreenline(row);
        this.edit();
    }
       public void showsgreenline(int index) {
     
        //Hien dong xanh trong table moi khi nhan next,prev,first,last;
        tblSach.setRowSelectionInterval(index, index);
    }
          private void init() {
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a");
                String text = formater.format(now);

                lblDongHo.setText(text);
            }
        }).start();
        
//   setLocationRelativeTo(null);
        
       // setTitle("Quản Lý Sách");
        this.fillTable(); // đổ dữ liệu nhân viên vào bảng
        tblSach.setDefaultEditor(Object.class, null);
    }
    
}
