/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import Dao.DocGiaDao;
import Entity.DocGia;
import Entity.Sach;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import utils.MsgBox;

/**
 *
 * @author duyvo
 */
public class QLSinhVien extends javax.swing.JPanel {

    DocGiaDao DGdao = new DocGiaDao();
    int row = 0;

    /**
     * Creates new form QLDocGia
     */
    public QLSinhVien() {
        initComponents();
        //  this.setLocationRelativeTo(null);
        init();
        tblDocGia.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GioiTinh = new javax.swing.ButtonGroup();
        main = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDocGia = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtMaDG = new button.textfield.TextField();
        txtNgaySinh = new button.textfield.TextField();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        txtTenDG = new button.textfield.TextField();
        txtSDT = new button.textfield.TextField();
        cboLop = new button.combobox.Combobox();
        txtMaNV = new button.textfield.TextField();
        txtGhiChu = new button.textfield.TextField();
        jLabel12 = new javax.swing.JLabel();
        myButton1 = new button.MyButton();
        myButton3 = new button.MyButton();
        myButton6 = new button.MyButton();
        myButton5 = new button.MyButton();
        myButton8 = new button.MyButton();
        myButton2 = new button.MyButton();
        myButton4 = new button.MyButton();
        myButton7 = new button.MyButton();
        lblDongHo = new javax.swing.JLabel();
        header = new component.menu_1();
        QLNhanVIen = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        lblMaSV = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTimKiem = new button.textfield.TextField();

        main.setBackground(new java.awt.Color(255, 204, 204));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDocGia.setBackground(new java.awt.Color(204, 204, 204));
        tblDocGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã đọc giả", "Tên đọc giả", "SDT", "Giới tính", "Lớp", "Mã nhân viên", "Ngày sinh", "Ghi chú"
            }
        ));
        tblDocGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblDocGiaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblDocGia);

        main.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 590, 390));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        jLabel7.setText("Lớp:");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        main.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        txtMaDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDGActionPerformed(evt);
            }
        });
        main.add(txtMaDG, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 120, -1));

        txtNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySinhActionPerformed(evt);
            }
        });
        main.add(txtNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 280, -1));

        GioiTinh.add(rdoNam);
        rdoNam.setText("Nam");
        rdoNam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rdoNamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rdoNamMouseExited(evt);
            }
        });
        rdoNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNamActionPerformed(evt);
            }
        });
        main.add(rdoNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 64, 34));

        GioiTinh.add(rdoNu);
        rdoNu.setText("Nữ");
        rdoNu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rdoNuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rdoNuMouseExited(evt);
            }
        });
        main.add(rdoNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 64, 34));

        txtTenDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDGActionPerformed(evt);
            }
        });
        main.add(txtTenDG, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 280, -1));

        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });
        main.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 280, -1));

        cboLop.setEditable(true);
        cboLop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12C7", "12C6", "12C5", "12C4", " " }));
        cboLop.setToolTipText("");
        cboLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLopActionPerformed(evt);
            }
        });
        main.add(cboLop, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 270, 40));

        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });
        main.add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 150, -1));

        txtGhiChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGhiChuActionPerformed(evt);
            }
        });
        main.add(txtGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 290, 110));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        jLabel12.setText("Ghi chú:");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        main.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, -1, -1));

        myButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bx-plus.png"))); // NOI18N
        myButton1.setColorClick(new java.awt.Color(255, 204, 153));
        myButton1.setRadius(10);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        main.add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, 50, 45));

        myButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bx-pencil.png"))); // NOI18N
        myButton3.setRadius(10);
        myButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton3ActionPerformed(evt);
            }
        });
        main.add(myButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 530, 50, 45));

        myButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bx-last-page.png"))); // NOI18N
        myButton6.setRadius(10);
        myButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton6ActionPerformed(evt);
            }
        });
        main.add(myButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 530, 50, 45));

        myButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bx-chevron-right.png"))); // NOI18N
        myButton5.setRadius(10);
        myButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton5ActionPerformed(evt);
            }
        });
        main.add(myButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 530, 50, 45));

        myButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bx-chevron-left.png"))); // NOI18N
        myButton8.setRadius(10);
        myButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton8ActionPerformed(evt);
            }
        });
        main.add(myButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 530, 50, 45));

        myButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bx-x.png"))); // NOI18N
        myButton2.setRadius(10);
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });
        main.add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, 50, 45));

        myButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bxs-news.png"))); // NOI18N
        myButton4.setRadius(10);
        myButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton4ActionPerformed(evt);
            }
        });
        main.add(myButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, 50, 45));

        myButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/first-page-regular-24.png"))); // NOI18N
        myButton7.setRadius(10);
        myButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton7ActionPerformed(evt);
            }
        });
        main.add(myButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 530, 50, 45));
        main.add(lblDongHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 600, 70, -1));

        QLNhanVIen.setBackground(new java.awt.Color(102, 102, 102));
        QLNhanVIen.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        QLNhanVIen.setForeground(new java.awt.Color(255, 255, 255));
        QLNhanVIen.setText("Quản lí sinh viên");
        QLNhanVIen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QLNhanVIenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QLNhanVIenMouseExited(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(401, 401, 401)
                .addComponent(QLNhanVIen)
                .addContainerGap(350, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QLNhanVIen)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        main.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        lblNhanVien.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        lblNhanVien.setText("Mã nhân viên");
        lblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNhanVienMouseExited(evt);
            }
        });
        main.add(lblNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        lblMaSV.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        lblMaSV.setText("Mã sinh viên");
        lblMaSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMaSVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMaSVMouseExited(evt);
            }
        });
        main.add(lblMaSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        lblTen.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        lblTen.setText("Tên sinh viên:");
        lblTen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTenMouseExited(evt);
            }
        });
        main.add(lblTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        lblNgaySinh.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        lblNgaySinh.setText("Ngày sinh:");
        lblNgaySinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNgaySinhMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNgaySinhMouseExited(evt);
            }
        });
        main.add(lblNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        lblGioiTinh.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        lblGioiTinh.setText("Giới tính:");
        lblGioiTinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGioiTinhMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGioiTinhMouseExited(evt);
            }
        });
        main.add(lblGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        lblSDT.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        lblSDT.setText("SDT:");
        lblSDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSDTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSDTMouseExited(evt);
            }
        });
        main.add(lblSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        jLabel13.setText("Tìm kiếm:");
        main.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });
        main.add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 153, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblDocGiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDocGiaMousePressed
        if (evt.getClickCount() == 2) {
            this.row = tblDocGia.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblDocGiaMousePressed

    private void txtMaDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDGActionPerformed

    private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySinhActionPerformed

    private void rdoNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNamActionPerformed

    private void txtTenDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDGActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void cboLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLopActionPerformed

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void txtGhiChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGhiChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGhiChuActionPerformed

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        insert();
    }//GEN-LAST:event_myButton1ActionPerformed

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
        update();
    }//GEN-LAST:event_myButton3ActionPerformed

    private void myButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton6ActionPerformed
        next();
    }//GEN-LAST:event_myButton6ActionPerformed

    private void myButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton5ActionPerformed
        last();
    }//GEN-LAST:event_myButton5ActionPerformed

    private void myButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton8ActionPerformed
        prev();
    }//GEN-LAST:event_myButton8ActionPerformed

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        delete();
    }//GEN-LAST:event_myButton2ActionPerformed

    private void myButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton4ActionPerformed
        clearForm();
    }//GEN-LAST:event_myButton4ActionPerformed

    private void myButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton7ActionPerformed
        first();
    }//GEN-LAST:event_myButton7ActionPerformed

    private void QLNhanVIenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QLNhanVIenMouseEntered
        // TODO add your handling code here:
        QLNhanVIen.setForeground(new Color(255, 255, 0));
    }//GEN-LAST:event_QLNhanVIenMouseEntered

    private void QLNhanVIenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QLNhanVIenMouseExited
        // TODO add your handling code here:
        QLNhanVIen.setForeground(new Color(242, 242, 242));
    }//GEN-LAST:event_QLNhanVIenMouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
               jLabel7.setForeground(new Color(0, 153, 51));

    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
                        jLabel7.setForeground(new Color(0, 0, 0));


    }//GEN-LAST:event_jLabel7MouseExited

    private void lblNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienMouseEntered
        // TODO add your handling code here:
        lblMaSV.setForeground(new Color(0, 153, 51));

    }//GEN-LAST:event_lblNhanVienMouseEntered

    private void lblNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienMouseExited
        // TODO add your handling code here:
        lblMaSV.setForeground(new Color(0, 0, 0));

    }//GEN-LAST:event_lblNhanVienMouseExited

    private void lblMaSVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaSVMouseEntered
        // TODO add your handling code here:
        lblMaSV.setForeground(new Color(0, 153, 51));
    }//GEN-LAST:event_lblMaSVMouseEntered

    private void lblMaSVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaSVMouseExited
        // TODO add your handling code here:
        lblMaSV.setForeground(new Color(0, 0, 0));

    }//GEN-LAST:event_lblMaSVMouseExited

    private void lblTenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTenMouseEntered
        // TODO add your handling code here:
        lblTen.setForeground(new Color(0, 153, 51));

    }//GEN-LAST:event_lblTenMouseEntered

    private void lblTenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTenMouseExited
        // TODO add your handling code here:
        lblTen.setForeground(new Color(0, 0, 0));

    }//GEN-LAST:event_lblTenMouseExited

    private void lblNgaySinhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNgaySinhMouseEntered
        // TODO add your handling code here:
        lblNgaySinh.setForeground(new Color(0, 153, 51));

    }//GEN-LAST:event_lblNgaySinhMouseEntered

    private void lblNgaySinhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNgaySinhMouseExited
        // TODO add your handling code here:
        lblNgaySinh.setForeground(new Color(0, 0, 0));


    }//GEN-LAST:event_lblNgaySinhMouseExited

    private void lblGioiTinhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGioiTinhMouseEntered
        // TODO add your handling code here:
        lblGioiTinh.setForeground(new Color(0, 153, 51));

    }//GEN-LAST:event_lblGioiTinhMouseEntered

    private void lblGioiTinhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGioiTinhMouseExited
        // TODO add your handling code here:
        lblGioiTinh.setForeground(new Color(0, 0, 0));

    }//GEN-LAST:event_lblGioiTinhMouseExited

    private void lblSDTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSDTMouseEntered
        // TODO add your handling code here:
        lblSDT.setForeground(new Color(0, 153, 51));

    }//GEN-LAST:event_lblSDTMouseEntered

    private void lblSDTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSDTMouseExited
        // TODO add your handling code here:
        lblSDT.setForeground(new Color(0, 0, 0));

    }//GEN-LAST:event_lblSDTMouseExited

    private void rdoNamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoNamMouseEntered
        // TODO add your handling code here:
        rdoNam.setForeground(new Color(0, 153, 51));

    }//GEN-LAST:event_rdoNamMouseEntered

    private void rdoNamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoNamMouseExited
        // TODO add your handling code here:
        rdoNam.setForeground(new Color(0, 0, 0));

    }//GEN-LAST:event_rdoNamMouseExited

    private void rdoNuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoNuMouseEntered
        // TODO add your handling code here:
        rdoNu.setForeground(new Color(0, 153, 51));

    }//GEN-LAST:event_rdoNuMouseEntered

    private void rdoNuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoNuMouseExited
        // TODO add your handling code here:                   
        rdoNu.setForeground(new Color(0, 0, 0));

    }//GEN-LAST:event_rdoNuMouseExited

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
                jLabel12.setForeground(new Color(0, 153, 51));

    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        // TODO add your handling code here:
                jLabel12.setForeground(new Color(0, 0, 0));

    }//GEN-LAST:event_jLabel12MouseExited

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        fillTable();
    }//GEN-LAST:event_txtTimKiemKeyReleased

    public void init() {
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a");
                String text = formater.format(now);

                lblDongHo.setText(text);
            }
        }).start();
        // getContentPane().setBackground(new Color(255, 255, 255));
        fillTable();
        updateStatus();
    }

    private void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblDocGia.getModel();
        model.setRowCount(0);
        try {
             String keyword = txtTimKiem.getText();
         
            List<DocGia> list = DGdao.selectByKeyword(keyword);
           
            for (DocGia dg : list) {
                Object[] row = {
                    dg.getMaDG(),
                    dg.getTenDG(),
                    dg.getSDT(),
                    dg.isGIOITINH() ? "Nam" : "Nữ",
                    dg.getLOP(),
                    dg.getMANV(),
                    dg.getNGAYSINH()

                };
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn dữ liệu nhân viên!");
            e.printStackTrace();
        }
    }

    private void insert() {
        DocGia dg = this.getForm();
        try {
            DGdao.insert(dg);
            this.fillTable();
            this.clearForm1();
            JOptionPane.showMessageDialog(this, "Thêm đọc giả mới thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Thêm đọc giả mới thất bại!");
            e.printStackTrace();

        }
    }

    private void update() {
        DocGia dg = this.getForm();

        try {
            DGdao.update(dg);
            this.fillTable();
            JOptionPane.showMessageDialog(this, "Cập nhật đọc giả thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cập nhật đọc giả thất bại!");
            e.printStackTrace();
        }

    }

    private void delete() {

        String madg = txtMaDG.getText();
        if (MsgBox.confirm(this, "Bạn có thực sự muốn xóa đọc giả này không?")) {
            try {
                DGdao.delete(madg);
                this.fillTable();
                this.clearForm1();
                MsgBox.alert(this, "Xóa đọc giả thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Xóa đọc giả thất bại!");
                e.printStackTrace();
            }
        }

    }

    private void clearForm() {
        DocGia dg = new DocGia();
        this.setForm(dg);
        this.row = -1;
        this.updateStatus();
    }

    private void clearForm1() {
        txtMaDG.setText("");
        txtGhiChu.setText("");
        txtMaNV.setText("");
        txtNgaySinh.setText("");
        txtSDT.setText("");
        txtTenDG.setText("");
        GioiTinh.clearSelection();
        cboLop.setSelectedItem("");
    }

    private void edit() {
        try {
            String manh = (String) tblDocGia.getValueAt(this.row, 0);
            DocGia model = DGdao.selectById(manh);
            if (model != null) {
                this.setForm(model);
                // jTabbedPane1.setSelectedIndex(0);
                this.updateStatus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void setForm(DocGia DG) {
        txtMaDG.setText(DG.getMaDG());
        txtTenDG.setText(DG.getTenDG());
        txtSDT.setText(DG.getSDT());
        cboLop.setSelectedItem(DG.getLOP());
        rdoNam.setSelected(DG.isGIOITINH());
        rdoNu.setSelected(!DG.isGIOITINH());
        txtNgaySinh.setText(DG.getNGAYSINH());
        txtMaNV.setText(DG.getMANV());

    }

    private DocGia getForm() {
        DocGia dg = new DocGia();
        dg.setMaDG(txtMaDG.getText());
        dg.setTenDG(txtTenDG.getText());
        dg.setSDT(txtSDT.getText());
        dg.setLOP(cboLop.getSelectedItem().toString());
        dg.setGIOITINH(rdoNam.isSelected());
        dg.setNGAYSINH(txtNgaySinh.getText());
        dg.setMANV(txtMaNV.getText());
        return dg;
    }

    public void showsgreenline(int index) {

        //Hien dong xanh trong table moi khi nhan next,prev,first,last;
        tblDocGia.setRowSelectionInterval(index, index);
    }

    private void first() {
        this.row = 0;
        this.edit();
        showsgreenline(row);
    }

    private void prev() {
        if (this.row > 0) {
            this.row--;
            showsgreenline(row);
            this.edit();
        }
    }

    private void next() {
        if (this.row < tblDocGia.getRowCount() - 1) {
            this.row++;
            showsgreenline(row);
            this.edit();
        }
    }

    private void last() {
        this.row = tblDocGia.getRowCount() - 1;
        showsgreenline(row);
        this.edit();
    }

    private void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblDocGia.getRowCount() - 1);
        // Trạng thái form
//        txtMaNhanVien.setEditable(!edit);
//        btnThem.setEnabled(!edit);
//        btnSua.setEnabled(edit);
//        btnXoa.setEnabled(edit);
//
//        // Trạng thái điều hướng
//        btnFirst.setEnabled(edit && !first);
//        btnPrev.setEnabled(edit && !first);
//        btnNext.setEnabled(edit && !last);
//        btnLast.setEnabled(edit && !last);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GioiTinh;
    private javax.swing.JLabel QLNhanVIen;
    private button.combobox.Combobox cboLop;
    private component.menu_1 header;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblMaSV;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTen;
    private javax.swing.JPanel main;
    private button.MyButton myButton1;
    private button.MyButton myButton2;
    private button.MyButton myButton3;
    private button.MyButton myButton4;
    private button.MyButton myButton5;
    private button.MyButton myButton6;
    private button.MyButton myButton7;
    private button.MyButton myButton8;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblDocGia;
    private button.textfield.TextField txtGhiChu;
    private button.textfield.TextField txtMaDG;
    private button.textfield.TextField txtMaNV;
    private button.textfield.TextField txtNgaySinh;
    private button.textfield.TextField txtSDT;
    private button.textfield.TextField txtTenDG;
    private button.textfield.TextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
